name: Backend CI

on:
  push:
    branches: [ "feature/backend" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/massivemarketmanager-backend

jobs:
  build_test_coverage:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & test (with JaCoCo)
        run: mvn -B -U clean verify

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            **/target/site/jacoco/**
            **/target/jacoco.exec

      - name: Coverage Summary (Markdown)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: target/site/jacoco/jacoco.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_complexity: true
          output: both

  docker:
    name: Docker build & push (GHCR)
    runs-on: ubuntu-latest
    needs: build_test_coverage
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/backend')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:feature-backend
